### ISSUE TITLE
rspec may be wrong after going over with one of Learn instructor

### ISSUE THREAD

**Issue by hebersandoval** [learn-co-curriculum/ttt-10-current-player#12]
def turn_count(board)
  counter = 0
  board.each do |char|
    if char = "X" || char = "O"
      counter += 1
    end
  end
  counter
end

def current_player(board)
  turn_count(board) % 2 == 0 ? "X" : "O"
end

**Comment by aturkewi** [comment]
@hscoder I just took a look at this and the spec seems like it's alright. There is an issue with your code on this line: `if char = "X" || char = "O"`. Rather than setting `char = "X"`, you want to be checking if `char == "X"`. 
If I've misunderstood this at all, just add some more detail to the issue and please feel free to re-open it.
